# Generated by Django 6.1 on 2026-08-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('ai_news', 'AI소식'), ('hands_on', '두드려봄'), ('opportunity', '기회'), ('tip', '꿀팁')], max_length=20, verbose_name='카테고리')),
                ('status', models.CharField(choices=[('producing', '제작중'), ('produced', '제작완료'), ('published', '발행완료'), ('canceled', '발행취소')], default='producing', max_length=20, verbose_name='상태')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행일')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='취소사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('due_date', models.DateField(verbose_name='마감일')),
                ('official_url', models.URLField(max_length=500, verbose_name='공식링크')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='episodes.episode', verbose_name='연결 에피소드')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='원본 URL')),
                ('collected_at', models.DateTimeField(verbose_name='수집일시')),
                ('summary', models.TextField(blank=True, verbose_name='요약')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='episodes.episode', verbose_name='연결 에피소드')),
            ],
        ),
    ]
