# Generated by Django 6.1 on 2026-08-09 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='episodes.episode', verbose_name='연결 에피소드'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='사건/주제')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('episodes', models.ManyToManyField(blank=True, related_name='topics', to='episodes.episode', verbose_name='연결 에피소드')),
            ],
        ),
    ]
