# Generated by Django 6.1 on 2026-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_alter_source_episode_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='임베딩 캐시'),
        ),
        migrations.AddField(
            model_name='topic',
            name='embedding_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='임베딩 캐시 키'),
        ),
    ]
